PROYECTO/ProyectoBDD-master/ProyectoBDD/Controllers/AsientosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoBDD.Models;

namespace ProyectoBDD.Controllers
{
    public class AsientosController : Controller
    {
        private ProyectoBDDEntities db = new ProyectoBDDEntities();

        // GET: Asientos
        public ActionResult Index()
        {
            var asiento = db.Asiento.Include(a => a.Avion).Include(a => a.TipoAsiento);
            return View(asiento.ToList());
        }

        // GET: Asientos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asiento asiento = db.Asiento.Find(id);
            if (asiento == null)
            {
                return HttpNotFound();
            }
            return View(asiento);
        }

        // GET: Asientos/Create
        public ActionResult Create()
        {
            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia");
            ViewBag.idTipoAsiento = new SelectList(db.TipoAsiento, "idTipoAsiento", "Tipo");
            return View();
        }

        // POST: Asientos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idAsiento,idAvion,idTipoAsiento,Cantidad")] Asiento asiento)
        {
            if (ModelState.IsValid)
            {
                db.Asiento.Add(asiento);
                db.SaveChanges();
                db.SP_INGRESAR_TRANLOG("Commit", "Insert", "Asiento");
                return RedirectToAction("Index");
            }

            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia", asiento.idAvion);
            ViewBag.idTipoAsiento = new SelectList(db.TipoAsiento, "idTipoAsiento", "Tipo", asiento.idTipoAsiento);
            return View(asiento);
        }

        // GET: Asientos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asiento asiento = db.Asiento.Find(id);
            if (asiento == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia", asiento.idAvion);
            ViewBag.idTipoAsiento = new SelectList(db.TipoAsiento, "idTipoAsiento", "Tipo", asiento.idTipoAsiento);
            return View(asiento);
        }

        // POST: Asientos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idAsiento,idAvion,idTipoAsiento,Cantidad")] Asiento asiento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asiento).State = EntityState.Modified;
                db.SaveChanges();
                db.SP_INGRESAR_TRANLOG("Commit", "Update", "Asiento");
                return RedirectToAction("Index");
            }
            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia", asiento.idAvion);
            ViewBag.idTipoAsiento = new SelectList(db.TipoAsiento, "idTipoAsiento", "Tipo", asiento.idTipoAsiento);
            return View(asiento);
        }

        // GET: Asientos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asiento asiento = db.Asiento.Find(id);
            if (asiento == null)
            {
                return HttpNotFound();
            }
            return View(asiento);
        }

        // POST: Asientos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Asiento asiento = db.Asiento.Find(id);
            db.Asiento.Remove(asiento);
            db.SaveChanges();
            db.SP_INGRESAR_TRANLOG("Commit", "Delete", "Asiento");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Controllers/AvionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoBDD.Models;

namespace ProyectoBDD.Controllers
{
    public class AvionesController : Controller
    {
        private ProyectoBDDEntities db = new ProyectoBDDEntities();

        // GET: Aviones
        public ActionResult Index()
        {
            var avion = db.Avion.Include(a => a.TipoAvion);
            return View(avion.ToList());
        }

        // GET: Aviones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avion avion = db.Avion.Find(id);
            if (avion == null)
            {
                return HttpNotFound();
            }
            return View(avion);
        }

        // GET: Aviones/Create
        public ActionResult Create()
        {
            ViewBag.idTipoAvion = new SelectList(db.TipoAvion, "idTipoAvion", "Tipo");
            return View();
        }

        // POST: Aviones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idAvion,idTipoAvion,Compañia,Carga,Alcance")] Avion avion)
        {
            if (ModelState.IsValid)
            {
                db.Avion.Add(avion);
                db.SaveChanges();
                db.SP_INGRESAR_TRANLOG("Commit", "Insert", "Avion");
                return RedirectToAction("Index");
            }

            ViewBag.idTipoAvion = new SelectList(db.TipoAvion, "idTipoAvion", "Tipo", avion.idTipoAvion);
            return View(avion);
        }

        // GET: Aviones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avion avion = db.Avion.Find(id);
            if (avion == null)
            {
                return HttpNotFound();
            }
            ViewBag.idTipoAvion = new SelectList(db.TipoAvion, "idTipoAvion", "Tipo", avion.idTipoAvion);
            return View(avion);
        }

        // POST: Aviones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idAvion,idTipoAvion,Compañia,Carga,Alcance")] Avion avion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(avion).State = EntityState.Modified;
                db.SaveChanges();
                db.SP_INGRESAR_TRANLOG("Commit", "Update", "Avion");
                return RedirectToAction("Index");
            }
            ViewBag.idTipoAvion = new SelectList(db.TipoAvion, "idTipoAvion", "Tipo", avion.idTipoAvion);
            return View(avion);
        }

        // GET: Aviones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avion avion = db.Avion.Find(id);
            if (avion == null)
            {
                return HttpNotFound();
            }
            return View(avion);
        }

        // POST: Aviones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Avion avion = db.Avion.Find(id);
            db.Avion.Remove(avion);
            db.SaveChanges();
            db.SP_INGRESAR_TRANLOG("Commit", "Delte", "Avion");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Aviones/Create.cshtml
@model ProyectoBDD.Models.Avion

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Avion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idTipoAvion, "idTipoAvion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idTipoAvion", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTipoAvion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Compañia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Compañia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Compañia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Carga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carga, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carga, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alcance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alcance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alcance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Aviones/Delete.cshtml
@model ProyectoBDD.Models.Avion

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Avion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Compañia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Compañia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carga)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carga)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alcance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alcance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAvion.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAvion.Tipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Aviones/Details.cshtml
@model ProyectoBDD.Models.Avion

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

<div>
    <h4>Avion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Compañia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Compañia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Carga)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carga)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alcance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alcance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoAvion.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoAvion.Tipo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idAvion }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Aviones/Edit.cshtml
@model ProyectoBDD.Models.Avion

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Avion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idAvion)

        <div class="form-group">
            @Html.LabelFor(model => model.idTipoAvion, "idTipoAvion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idTipoAvion", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTipoAvion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Compañia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Compañia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Compañia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Carga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Carga, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Carga, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alcance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alcance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alcance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Aviones/Index.cshtml
@model IEnumerable<ProyectoBDD.Models.Avion>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Ver Asientos", "Index", "Asientos")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Compañia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Carga)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Alcance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoAvion.Tipo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Compañia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Carga)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Alcance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoAvion.Tipo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idAvion }) |
                @Html.ActionLink("Details", "Details", new { id = item.idAvion }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.idAvion })
            </td>
        </tr>
    }

</table>