PROYECTO/ProyectoBDD-master/ProyectoBDD/Models/Vuelo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelo()
        {
            this.Escala = new HashSet<Escala>();
            this.VueloPasajero = new HashSet<VueloPasajero>();
        }
    
        public int idVuelo { get; set; }
        public Nullable<int> idAvion { get; set; }
        public bool Estatus { get; set; }
        public string CiudadOrigen { get; set; }
        public string CiudadDestino { get; set; }
        public string AeropuertoOrigen { get; set; }
        public string AeropuertoDestino { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public string Jornada { get; set; }
    
        public virtual Avion Avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Escala> Escala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VueloPasajero> VueloPasajero { get; set; }
    }
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Controllers/EscalasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoBDD.Models;

namespace ProyectoBDD.Controllers
{
    public class EscalasController : Controller
    {
        private ProyectoBDDEntities db = new ProyectoBDDEntities();
        public static int idVuelo;

        // GET: Escalas
        public ActionResult Index()
        {
            var escala = db.Escala.Include(e => e.Vuelo);
            return View(escala.ToList());
        }

        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            try
            {
                idVuelo = Convert.ToInt32(collection["idVuelo"]);
                return RedirectToAction("Search");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Escalas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Escala escala = db.Escala.Find(id);
            if (escala == null)
            {
                return HttpNotFound();
            }
            return View(escala);
        }

        // GET: Escalas/Create
        public ActionResult Create()
        {
            ViewBag.idVuelo = new SelectList(db.Vuelo, "idVuelo", "idVuelo");
            return View();
        }

        // POST: Escalas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idEscala,idVuelo,Destino,FechaHora")] Escala escala)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.SP_INGRESAR_ESCALA(escala.idVuelo, escala.Destino, escala.FechaHora);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    int i = ex.InnerException.Message.IndexOf("Transaction");
                    ViewData["Error"] = ex.InnerException.Message.Substring(0, i);
                }
            }

            ViewBag.idVuelo = new SelectList(db.Vuelo, "idVuelo", "idVuelo", escala.idVuelo);
            return View(escala);
        }

        // GET: Escalas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Escala escala = db.Escala.Find(id);
            if (escala == null)
            {
                return HttpNotFound();
            }
            ViewBag.idVuelo = new SelectList(db.Vuelo, "idVuelo", "idVuelo", escala.idVuelo);
            return View(escala);
        }

        // POST: Escalas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idEscala,idVuelo,Destino,FechaHora")] Escala escala)
        {
            if (ModelState.IsValid)
            {
                db.Entry(escala).State = EntityState.Modified;
                db.SaveChanges();
                db.SP_INGRESAR_TRANLOG("Commit", "Update", "Escala");
                return RedirectToAction("Index");
            }
            ViewBag.idVuelo = new SelectList(db.Vuelo, "idVuelo", "idVuelo", escala.idVuelo);
            return View(escala);
        }

        // GET: Escalas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Escala escala = db.Escala.Find(id);
            if (escala == null)
            {
                return HttpNotFound();
            }
            return View(escala);
        }

        // POST: Escalas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Escala escala = db.Escala.Find(id);
            db.Escala.Remove(escala);
            db.SaveChanges();
            db.SP_INGRESAR_TRANLOG("Commit", "Delete", "Escala");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search()
        {
            return View(db.SP_VUELO_ESCALAS(idVuelo).ToList());
        }
    }
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Controllers/VuelosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoBDD.Models;

namespace ProyectoBDD.Controllers
{
    public class VuelosController : Controller
    {
        private ProyectoBDDEntities db = new ProyectoBDDEntities();

        // GET: Vuelos
        public ActionResult Index()
        {
            var vuelo = db.Vuelo.Include(v => v.Avion);
            return View(vuelo.ToList());
        }

        // GET: Vuelos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vuelo vuelo = db.Vuelo.Find(id);
            if (vuelo == null)
            {
                return HttpNotFound();
            }
            return View(vuelo);
        }

        // GET: Vuelos/Create
        public ActionResult Create()
        {
            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia");
            return View();
        }

        // POST: Vuelos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idVuelo,idAvion,Estatus,CiudadOrigen,CiudadDestino,AeropuertoOrigen,AeropuertoDestino,FechaSalida,FechaLlegada,Jornada")] Vuelo vuelo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.SP_INGRESAR_VUELO(vuelo.idAvion, vuelo.CiudadOrigen, vuelo.CiudadDestino, vuelo.AeropuertoOrigen, vuelo.AeropuertoDestino, vuelo.FechaSalida, vuelo.FechaLlegada);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewData["Error"] = ex.InnerException.Message;
                }
            }

            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia", vuelo.idAvion);
            return View(vuelo);
        }

        // GET: Vuelos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vuelo vuelo = db.Vuelo.Find(id);
            if (vuelo == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia", vuelo.idAvion);
            return View(vuelo);
        }

        // POST: Vuelos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idVuelo,idAvion,Estatus,CiudadOrigen,CiudadDestino,AeropuertoOrigen,AeropuertoDestino,FechaSalida,FechaLlegada,Jornada")] Vuelo vuelo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vuelo).State = EntityState.Modified;
                db.SaveChanges();
                db.SP_INGRESAR_TRANLOG("Commit", "Update", "Vuelo");
                return RedirectToAction("Index");
            }
            ViewBag.idAvion = new SelectList(db.Avion, "idAvion", "Compañia", vuelo.idAvion);
            return View(vuelo);
        }

        // GET: Vuelos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vuelo vuelo = db.Vuelo.Find(id);
            if (vuelo == null)
            {
                return HttpNotFound();
            }
            return View(vuelo);
        }

        // POST: Vuelos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                db.SP_CANCELAR_VUELO(id);
                db.SP_INGRESAR_TRANLOG("Commit", "Update", "Pasajero");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewData["Error"] = ex.InnerException.Message;
            }
            Vuelo vuelo = db.Vuelo.Find(id);
            return View(vuelo);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Vuelos/Create.cshtml
@model ProyectoBDD.Models.Vuelo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vuelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idAvion, "idAvion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idAvion", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idAvion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiudadOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CiudadOrigen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CiudadOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiudadDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CiudadDestino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CiudadDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AeropuertoOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AeropuertoOrigen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AeropuertoOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AeropuertoDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AeropuertoDestino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AeropuertoDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaLlegada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaLlegada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaLlegada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Vuelos/Delete.cshtml
@model ProyectoBDD.Models.Vuelo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vuelo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiudadOrigen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadOrigen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiudadDestino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadDestino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AeropuertoOrigen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AeropuertoOrigen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AeropuertoDestino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AeropuertoDestino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaLlegada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaLlegada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avion.Compañia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avion.Compañia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Vuelos/Details.cshtml
@model ProyectoBDD.Models.Vuelo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

<div>
    <h4>Vuelo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiudadOrigen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadOrigen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CiudadDestino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CiudadDestino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AeropuertoOrigen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AeropuertoOrigen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AeropuertoDestino)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AeropuertoDestino)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaLlegada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaLlegada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avion.Compañia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avion.Compañia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idVuelo }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Vuelos/Edit.cshtml
@model ProyectoBDD.Models.Vuelo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vuelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idVuelo)

        <div class="form-group">
            @Html.LabelFor(model => model.idAvion, "idAvion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idAvion", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idAvion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiudadOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CiudadOrigen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CiudadOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiudadDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CiudadDestino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CiudadDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AeropuertoOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AeropuertoOrigen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AeropuertoOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AeropuertoDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AeropuertoDestino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AeropuertoDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaLlegada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaLlegada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaLlegada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROYECTO/ProyectoBDD-master/ProyectoBDD/Views/Vuelos/Index.cshtml
@model IEnumerable<ProyectoBDD.Models.Vuelo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<div class="text-center">
    <p style="font-size:larger; color:red">@ViewData["Error"]</p>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Ver Escalas", "Index", "Escalas")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Estatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CiudadOrigen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CiudadDestino)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AeropuertoOrigen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AeropuertoDestino)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaLlegada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Avion.Compañia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Estatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CiudadOrigen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CiudadDestino)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AeropuertoOrigen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AeropuertoDestino)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaSalida)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaLlegada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Avion.Compañia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.idVuelo }) |
            @Html.ActionLink("Details", "Details", new { id=item.idVuelo }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.idVuelo })
        </td>
    </tr>
}

</table>